version: "3"
services:
  xray:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/xray:v0.0.3
    environment:
      XRAY_SHELL: 'webscan --listen 0.0.0.0:9811 --webhook-output http://usb:5005/api/v1/xray'
    restart: always

  usb:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/usb:v0.0.3
    restart: always
    volumes:
      - ./config-tutorial.ini:/opt/config-tutorial.ini

  mitmproxy:
    image: registry.cn-beijing.aliyuncs.com/huoxian_pub/mitmproxy:v0.0.3
    restart: always
    environment:
      XRAY_URL: 'xray'
    ports:
      - '10802:10802'