# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [ created, edited ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run GoReleaser
      if: "!github.event.release.prerelease"
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set the value
        id: release
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          ID=`echo ${TAG_NAME##v}`
          echo "tag_version=$ID" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
      - name: Build and push usb
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/huoxian_pub/usb:v${{ env.tag_version }}
      - name: Build and push mitmproxy
        uses: docker/build-push-action@v3
        with:
          file: ./deploy/mitmproxy/Dockerfile
          context: ./deploy/mitmproxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/huoxian_pub/mitmproxy:v${{ env.tag_version }}
      - name: Build and push xray
        uses: docker/build-push-action@v3
        with:
          file: ./deploy/xray/Dockerfile
          context: ./deploy/xray
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/huoxian_pub/xray:v${{ env.tag_version }}